// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ZwQWyVKIsIQJUUjeDJf6eN83qWaq0Oc',
    appId: '1:797336178450:web:8d22e8d72d61cd5b4f2dcb',
    messagingSenderId: '797336178450',
    projectId: 'edu-vista-fdeec',
    authDomain: 'edu-vista-fdeec.firebaseapp.com',
    storageBucket: 'edu-vista-fdeec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmnZ6rZrbj18DdFo0sBlV1MgY2fpT8O-4',
    appId: '1:797336178450:android:44cf8a628d238ede4f2dcb',
    messagingSenderId: '797336178450',
    projectId: 'edu-vista-fdeec',
    storageBucket: 'edu-vista-fdeec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrL-YWowfumprZvtRXbB65DOYlPgcUe54',
    appId: '1:797336178450:ios:220d9306b8e461104f2dcb',
    messagingSenderId: '797336178450',
    projectId: 'edu-vista-fdeec',
    storageBucket: 'edu-vista-fdeec.appspot.com',
    iosBundleId: 'com.example.coursesApp',
  );
}
